---
version: '3'
set: [errexit, nounset, pipefail]

tasks:
  default:
    desc: "List all tasks"
    cmds:
    - task -l

  render:
    desc: "Render the templates"
    cmds:
    - task: plato render

  setup:
    desc: "Setup environment"
    cmds:
    - bash setup.sh

  deploy:
    desc: "Deploy all apps"
    cmds:
    - task: cf-env:all
    - task: resume:all
    - task: jcio:all
    - task: home-info:all
    - task: irvisualizer:all
    - task: backman:all
    - task: pgweb:all
    - task: item-monitor:all
    - task: image-puller:all
    - task: repo-mirrorer:all
    - task: wireguard:all
    - task: deploy-job:all
    - task: list-apps
    - task: cleanup

  list-apps:
    desc: "List all running apps"
    cmds:
    - bash list_apps.sh

  cleanup:
    desc: "Cleanup environment, remove confidential files"
    cmds:
    - bash cleanup.sh

includes:
  backman: ./backman
  cf-env: ./cf-env
  deploy-job: ./deploy-job
  home-info: ./home-info
  image-puller: ./image-puller
  irvisualizer: ./irvisualizer
  item-monitor: ./item-monitor
  jcio: ./jcio
  pgweb: ./pgweb
  repo-mirrorer: ./repo-mirrorer
  resume: ./resume
  wireguard: ./wireguard
