#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("_ytt.lib.yml", "labels")

---
apiVersion: v1
kind: Secret
metadata:
  name: irvisualizer
  namespace: irvisualizer
  labels: #@ labels("secret")
  annotations:
    kapp.k14s.io/versioned: ""
type: Opaque
stringData:
  AUTH_USERNAME: #@ data.values.ircollector.auth.username
  AUTH_PASSWORD: #@ data.values.ircollector.auth.password
  IR_USERNAME: #@ data.values.ircollector.iracing_auth.username
  IR_PASSWORD: #@ data.values.ircollector.iracing_auth.password
  LOGGLY_TOKEN: #@ data.values.loggly_token
  DB_URI: #@ data.values.db_uri
  PROBE_AUTHORIZATION: #@ 'Basic ' + base64.encode(data.values.ircollector.auth.username + ':' + data.values.ircollector.auth.password)
