#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:assert", "assert")
#@ load("_ytt.lib.yml", "labels", "connstr")

#@ if len(data.values.loggly_token) == 0 or data.values.loggly_token == "token":
#@  assert.fail("loggly_token is missing or invalid")
#@ end
#@ if len(data.values.auth.username) == 0 or data.values.auth.username == "username":
#@  assert.fail("auth.username is missing or invalid")
#@ end
#@ if len(data.values.auth.password) == 0 or data.values.auth.password == "password":
#@  assert.fail("auth.password is missing or invalid")
#@ end
#@ if len(data.values.ircollector.iracing_auth.username) == 0 or data.values.ircollector.iracing_auth.username == "username":
#@  assert.fail("ircollector.iracing_auth.username is missing or invalid")
#@ end
#@ if len(data.values.ircollector.iracing_auth.password) == 0 or data.values.ircollector.iracing_auth.password == "password":
#@  assert.fail("ircollector.iracing_auth.password is missing or invalid")
#@ end
#@ if len(data.values.database.host) == 0 or data.values.database.host == "host":
#@   assert.fail("database.host is missing or invalid")
#@ end
#@ if len(data.values.database.database) == 0 or data.values.database.database == "dbname":
#@   assert.fail("database.database is missing or invalid")
#@ end
#@ if len(data.values.database.username) == 0 or data.values.database.username == "username":
#@   assert.fail("database.username is missing or invalid")
#@ end
#@ if len(data.values.database.password) == 0 or data.values.database.password == "password":
#@   assert.fail("database.password is missing or invalid")
#@ end
---
apiVersion: v1
kind: Secret
metadata:
  name: irvisualizer
  namespace: irvisualizer
  labels: #@ labels("secret")
  annotations:
    kapp.k14s.io/versioned: ""
type: Opaque
stringData:
  AUTH_USERNAME: #@ data.values.auth.username
  AUTH_PASSWORD: #@ data.values.auth.password
  IR_USERNAME: #@ data.values.ircollector.iracing_auth.username
  IR_PASSWORD: #@ data.values.ircollector.iracing_auth.password
  LOGGLY_TOKEN: #@ data.values.loggly_token
  DB_URI: #@ connstr(data.values.database.username, data.values.database.password, data.values.database.host, data.values.database.database)
  PROBE_AUTHORIZATION: #@ 'Basic ' + base64.encode(data.values.auth.username + ':' + data.values.auth.password)
