#@ load("@ytt:data", "data")
#@ load("_ytt.lib.yml", "labels", "podAntiAffinity")

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-monitor
  namespace: item-monitor
  labels: #@ labels("monitor")
spec:
  selector:
    matchLabels: #@ labels("monitor")
  replicas: 1
  revisionHistoryLimit: 5
  template:
    metadata:
      labels: #@ labels("monitor")
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
    spec:
      serviceAccountName: item-monitor
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      affinity: #@ podAntiAffinity("monitor")
      containers:
      - name: item-monitor
        image: #@ data.values.item_monitor.image
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
        env:
        - name: PORT
          value: "8080"
        - name: TZ
          value: "Europe/Zurich"
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        volumeMounts:
        - mountPath: /item-monitor/app/config.yaml
          name: config
          subPath: config.yaml
      volumes:
      - name: config
        secret:
          secretName: item-monitor
