---
version: '3'
set: [errexit, nounset, pipefail]

tasks:
  deploy:
    desc: "Deploy app"
    dir: '{{.TASKFILE_DIR}}'
    cmds:
    - bash deploy.sh

  diff:
    desc: "Run a diff to the kubernetes cluster"
    dir: '{{.TASKFILE_DIR}}'
    cmds:
    - bash diff.sh

  status:
    desc: "Display the app status"
    dir: '{{.TASKFILE_DIR}}'
    cmds:
    - bash status.sh

  lock_image:
    desc: "Lock images"
    dir: '{{.TASKFILE_DIR}}'
    cmds:
    - bash lock_image.sh
