#@data/values
---
enable_network_policy: true

jcio:
  replicas: 1
  image: "jamesclonk/jcio-frontend:942d37e2fadd52c250b1732899aa6566396d4f91"

moviedb:
  frontend:
    replicas: 1
    image: "jamesclonk/moviedb-frontend:87286a8dd8d0ff6fb9108880b51887854ad0872c"

  backend:
    replicas: 1
    image: "jamesclonk/moviedb-backend:6abf341bd5f1d050e43ac34be3f56b0f72e4af75"
