#@ load("@ytt:data", "data")
#@ load("@ytt:assert", "assert")
#@ load("_ytt.lib.yml", "labels")

#@ if len(data.values.image_puller.images) == 0:
#@  assert.fail("image_puller.images are missing")
#@ end
#@ for idx in range(len(data.values.image_puller.images)):
#@   image = data.values.image_puller.images[idx]
#@   if len(image) < 10:
#@     assert.fail("image_puller.images[" + str(idx) + "] is invalid")
#@   end
#@ end
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: image-puller-config
  namespace: image-puller
  labels: #@ labels()
  annotations:
    kapp.k14s.io/versioned: ""
#@yaml/text-templated-strings
data:
  images.dat: |
    (@- for image in data.values.image_puller.images: @)
    (@= image @)
    (@- end @)
