#@ load("@ytt:data", "data")
#@ load("_ytt.lib.yml", "labels")

#@ def jobTemplate():
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: image-puller
        image: #@ data.values.image_puller.image
        volumeMounts:
        - name: image-puller-config
          mountPath: /app/images.dat
          subPath: images.dat
      volumes:
      - name: image-puller-config
        configMap:
          name: image-puller-config
      resources:
        requests:
          memory: "64Mi"
          cpu: "25m"
        limits:
          memory: "128Mi"
          cpu: "100m"
#@ end

#@ if data.values.image_puller.cronjob:
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: image-puller
  namespace: image-puller
  labels: #@ labels()
spec:
  schedule: "37 13 * * 0,3"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec: #@ jobTemplate()
#@ end

#@ if data.values.image_puller.run_job:
---
apiVersion: batch/v1
kind: Job
metadata:
  name: image-puller
  namespace: image-puller
  labels: #@ labels()
spec: #@ jobTemplate()
#@ end
