#@ load("@ytt:data", "data")
#@ load("_ytt.lib.yaml", "labels")

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: deploy-job
  namespace: deploy-job
  labels: #@ labels()
  annotations:
    kapp.k14s.io/versioned: ""
data:
  deploy.sh: |
    #!/bin/bash
    set -e
    set -u
    set -o pipefail

    date
    sleep 33
    export PATH="$HOME/bin:$PATH"

    git clone https://github.com/JamesClonk/k8s-infrastructue.git
    git clone https://github.com/JamesClonk/k8s-deployments.git
    git clone https://github.com/JamesClonk/k8s-testing.git
    cd k8s-deployments
    task deploy
