#@ load("@ytt:data", "data")
#@ load("_ytt.lib.yaml", "labels")

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: deploy-job
  namespace: deploy-job
  labels: #@ labels()
spec:
  schedule: "37 09 * * 1"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          initContainers:
          - name: init
            image: #@ data.values.busybox.image
            command:
            - sh
            - -c
            - sysctl -w net.ipv4.ip_forward=1 && sysctl -w net.ipv4.conf.all.forwarding=1
            securityContext:
              privileged: true
              capabilities:
                add:
                - NET_ADMIN
          containers:
          - name: deploy-job
            image: #@ data.values.deploy_job.image
            command:
            - /bin/bash
            - /root/script/deploy.sh
            securityContext:
              privileged: true
              capabilities:
                add:
                - NET_ADMIN
            volumeMounts:
            - name: age-file
              mountPath: /root/.config/sops/age/keys.txt
              subPath: keys.txt
            - name: deploy-script
              mountPath: /root/script/deploy.sh
              subPath: deploy.sh
          volumes:
          - name: age-file
            secret:
              secretName: deploy-job
          - name: deploy-script
            configMap:
              name: deploy-job
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
