#@ load("@ytt:data", "data")
#@ load("_ytt.lib.yaml", "labels")

---
apiVersion: v1
kind: Secret
metadata:
  name: deploy-job
  namespace: deploy-job
  labels: #@ labels()
  annotations:
    kapp.k14s.io/versioned: ""
type: Opaque
stringData:
  keys.txt: #@ data.values.secrets.age_key
