#@ load("@ytt:data", "data")
#@ load("@ytt:assert", "assert")
#@ load("_ytt.lib.yml", "labels", "connstr")

#@ if len(data.values.secrets.home_info.auth.username) == 0 or data.values.secrets.home_info.auth.username == "username":
#@  assert.fail("secrets.home_info.auth.username is missing or invalid")
#@ end
#@ if len(data.values.secrets.home_info.auth.password) == 0 or data.values.secrets.home_info.auth.password == "password":
#@  assert.fail("secrets.home_info.auth.password is missing or invalid")
#@ end
#@ if len(data.values.secrets.home_info.database.host) == 0 or data.values.secrets.home_info.database.host == "host":
#@   assert.fail("secrets.home_info.database.host is missing or invalid")
#@ end
#@ if len(data.values.secrets.home_info.database.database) == 0 or data.values.secrets.home_info.database.database == "dbname":
#@   assert.fail("secrets.home_info.database.database is missing or invalid")
#@ end
#@ if len(data.values.secrets.home_info.database.username) == 0 or data.values.secrets.home_info.database.username == "username":
#@   assert.fail("secrets.home_info.database.username is missing or invalid")
#@ end
#@ if len(data.values.secrets.home_info.database.password) == 0 or data.values.secrets.home_info.database.password == "password":
#@   assert.fail("secrets.home_info.database.password is missing or invalid")
#@ end
#@ if len(data.values.secrets.home_info.slack.token) == 0 or data.values.secrets.home_info.slack.token == "token":
#@  assert.fail("secrets.home_info.slack.token is missing or invalid")
#@ end
#@ if len(data.values.secrets.home_info.teams.webhook_url) == 0 or data.values.secrets.home_info.teams.webhook_url == "http://example/deadbeef":
#@  assert.fail("secrets.home_info.teams.webhook_url is missing or invalid")
#@ end
---
apiVersion: v1
kind: Secret
metadata:
  name: home-info
  namespace: home-info
  labels: #@ labels("secret")
  annotations:
    kapp.k14s.io/versioned: ""
type: Opaque
stringData:
  HOME_INFO_DB_URI: #@ connstr(data.values.secrets.home_info.database.username, data.values.secrets.home_info.database.password, data.values.secrets.home_info.database.host, data.values.secrets.home_info.database.database)
  AUTH_USERNAME: #@ data.values.secrets.home_info.auth.username
  AUTH_PASSWORD: #@ data.values.secrets.home_info.auth.password
  SLACK_CHANNEL: "USER_Fabio"
  SLACK_TOKEN: #@ data.values.secrets.home_info.slack.token
  SLACK_DEBUG: "false"
  TEAMS_WEBHOOK_URL: #@ data.values.secrets.home_info.teams.webhook_url
  CONFIG_BEDROOM_HUMIDITY_SENSOR_ID: "5"
  CONFIG_BEDROOM_TEMPERATURE_SENSOR_ID: "4"
  CONFIG_BEDROOM_CO2_SENSOR_ID: "31"
  CONFIG_FORECAST_TEMPERATURE_SENSOR_ID: "3"
  CONFIG_FORECAST_HUMIDITY_SENSOR_ID: "27"
  CONFIG_FORECAST_WIND_SPEED_SENSOR_ID: "28"
  CONFIG_HOME_OFFICE_HUMIDITY_SENSOR_ID: "7"
  CONFIG_HOME_OFFICE_TEMPERATURE_SENSOR_ID: "6"
  CONFIG_LIVING_ROOM_HUMIDITY_SENSOR_ID: "2"
  CONFIG_LIVING_ROOM_TEMPERATURE_SENSOR_ID: "1"
  CONFIG_LIVING_ROOM_CO2_SENSOR_ID: "22"
  CONFIG_PLANT_ROOM_HUMIDITY_SENSOR_ID: "17"
  CONFIG_PLANT_ROOM_TEMPERATURE_SENSOR_ID: "16"
  CONFIG_GALLERY_HUMIDITY_SENSOR_ID: "26"
  CONFIG_GALLERY_TEMPERATURE_SENSOR_ID: "25"
  CONFIG_GALLERY_AIR_PRESSURE_SENSOR_ID: "30"
  CONFIG_BASEMENT_HUMIDITY_SENSOR_ID: "24"
  CONFIG_BASEMENT_TEMPERATURE_SENSOR_ID: "23"
  CONFIG_WEIGHT_SENSOR_ID: "19"
  CONFIG_CALORIES_SENSOR_ID: "20"
  CONFIG_BODYFAT_SENSOR_ID: "21"
