#@ load("@ytt:data", "data")
#@ load("_ytt.lib.yml", "labels")

---
apiVersion: v1
kind: Secret
metadata:
  name: home-info
  namespace: home-info
  labels: #@ labels("secret")
  annotations:
    kapp.k14s.io/versioned: ""
type: Opaque
stringData:
  HOME_INFO_DB_URI: #@ data.values.home_info.db_uri
  AUTH_USERNAME: #@ data.values.home_info.auth.username
  AUTH_PASSWORD: #@ data.values.home_info.auth.password
  SLACK_CHANNEL: "USER_Fabio"
  SLACK_TOKEN: #@ data.values.home_info.slack.token
  SLACK_DEBUG: "false"
  TEAMS_WEBHOOK_URL: #@ data.values.home_info.teams.webhook_url
  CONFIG_BEDROOM_HUMIDITY_SENSOR_ID: "5"
  CONFIG_BEDROOM_TEMPERATURE_SENSOR_ID: "4"
  CONFIG_FORECAST_TEMPERATURE_SENSOR_ID: "3"
  CONFIG_HOME_OFFICE_HUMIDITY_SENSOR_ID: "7"
  CONFIG_HOME_OFFICE_TEMPERATURE_SENSOR_ID: "6"
  CONFIG_LIVING_ROOM_HUMIDITY_SENSOR_ID: "2"
  CONFIG_LIVING_ROOM_TEMPERATURE_SENSOR_ID: "1"
  CONFIG_PLANT_ROOM_HUMIDITY_SENSOR_ID: "17"
  CONFIG_PLANT_ROOM_TEMPERATURE_SENSOR_ID: "16"
