#@data/values
---
item_monitor:
  image: "jamesclonk/item-monitor:1022361"

  monitors:
  - name: galaxus
    items:
    - name: Scarpa Vapor V
      url: https://www.galaxus.ch/de/s3/product/scarpa-vapor-v-kletterschuhe-42-kletterschuhe-10611477
      value: 125
      regex: <meta property="product:price:amount" content="([0-9.]+)"\/>
    - name: Scarpa Vapor S
      url: https://www.galaxus.ch/de/s3/product/scarpa-vapor-s-42-kletterschuhe-24594482
      value: 125
      regex: <meta property="product:price:amount" content="([0-9.]+)"\/>
    - name: Scarpa Arpia V
      url: https://www.galaxus.ch/de/s3/product/scarpa-arpia-v-42-kletterschuhe-41901081
      value: 110
      regex: <meta property="product:price:amount" content="([0-9.]+)"\/>
