#@data/values
---
item_monitor:
  image: "jamesclonk/item-monitor:1022361"

  monitors:
  - name: galaxus
    items:
    - name: Philips Hue GU10 3x
      url: https://www.galaxus.ch/de/s14/product/philips-hue-white-color-ambiance-bt-gu10-570-w-350-lm-3-x-g-leuchtmittel-16446773
      value: 100
      regex: <meta property="product:price:amount" content="([0-9.]+)"\/>
    - name: Philips Hue Full-Set Combo GU10 3x
      url: https://www.galaxus.ch/de/s14/product/philips-hue-white-color-ambiance-starterset-gu10-570-w-350-lm-3-x-g-leuchtmittel-11235548
      value: 131
      regex: <meta property="product:price:amount" content="([0-9.]+)"\/>
    - name: HP Thunderbolt Docking Station
      url: https://www.galaxus.ch/de/s1/product/hp-thunderbolt-120-w-g4-dock-thunderbolt-dockingstation-usb-hub-21359396
      value: 190
      regex: <meta property="product:price:amount" content="([0-9.]+)"\/>
    - name: HP Thunderbolt G4 Docking Station
      url: https://www.galaxus.ch/de/s1/product/hp-thunderbolt-g4-dock-thunderbolt-2-ports-dockingstation-usb-hub-21359395
      value: 190
      regex: <meta property="product:price:amount" content="([0-9.]+)"\/>
