#@data/values
---
domains:
- "${INGRESS_DOMAIN}"

home_info:
  replicas: 1
  image: "jamesclonk/home-info-dashboard:a39e45f37ace94bec9b8589d1b443a0f9b525e81"

  enable_network_policy: true

  database:
    host: "${HOME_INFO_DB_HOST}"
    database: "${HOME_INFO_DB_NAME}"
    username: "${HOME_INFO_DB_USERNAME}"
    password: "${HOME_INFO_DB_PASSWORD}"

  auth:
    username: "${HOME_INFO_AUTH_USERNAME}"
    password: "${HOME_INFO_AUTH_PASSWORD}"
  slack:
    token: "${HOME_INFO_SLACK_TOKEN}"
  teams:
    webhook_url: "${HOME_INFO_TEAMS_WEBHOOK_URL}"
