#@data/values
---
image_puller:
  image: "jamesclonk/image-puller:ef9d2a272282c4ccb199d146e71a4d8fbbdad15c"

  cronjob: true
  run_job: false

  images:
  #! direct jc.io stuff
  - "jamesclonk/image-puller:ef9d2a272282c4ccb199d146e71a4d8fbbdad15c"
  - "jamesclonk/repo-mirrorer:0f100962dfc32b5a15da6cc73ba3f98e007832a8"
  - "jamesclonk/backman:1.28.1"
  - "jamesclonk/cf-env:89d20c44e3d6b1a4e0c0502e9d1f5bc908e81264"
  - "jamesclonk/home-info-dashboard:dc579d1540c9f24b9a8e9a86841a32637fa2f537"
  - "jamesclonk/irvisualizer:2ed9d65b47cfa5dda4765748e4b1c3a94bed1ea3"
  - "jamesclonk/ircollector:381f705a930f586470ba157451619e853cd584ee"
  - "jamesclonk/irdiscordbot:5fb803c78ce9c994701b2d718ca10110da71935f"
  - "jamesclonk/jcio-frontend:d87aec9e0beccc690ad2833f899d39dbe6af6203"
  - "jamesclonk/moviedb-frontend:87286a8dd8d0ff6fb9108880b51887854ad0872c"
  - "jamesclonk/moviedb-backend:6abf341bd5f1d050e43ac34be3f56b0f72e4af75"
  - "jamesclonk/basic-auth:678636aaca212f20c4e263d05b75efabdc6aef2c"
  - "jamesclonk/pgbackup:aee0398bd7634f209ecd7e1ec03f55002c3c3a57"
  - "jamesclonk/mcbackup:f3b390668671bba69835320ab82824470f6404a4"
  - "jamesclonk/resume:e104fbe6f04158fb99d2d69d905dfe6412f3b2e6"

  #! other stuff
  - "jamesclonk/web-container:latest"
  - "jamesclonk/docker-simple:latest"

  #! kuard
  - "gcr.io/kuar-demo/kuard-amd64:v0.10.0-green"

  #! postgres
  - "edoburu/pgbouncer:1.12.0"
  - "postgres:12"
  - "wrouesnel/postgres_exporter:v0.8.0"

  #! pgweb
  - "sosedoff/pgweb:0.11.7"

  #! cert-manager
  - "quay.io/jetstack/cert-manager-cainjector:v1.6.1"
  - "quay.io/jetstack/cert-manager-controller:v1.6.1"
  - "quay.io/jetstack/cert-manager-webhook:v1.6.1"

  #! ingress-nginx
  - "docker.io/jettech/kube-webhook-certgen:v1.5.1"
  - "jamesclonk/basic-auth:678636aaca212f20c4e263d05b75efabdc6aef2c"
  - "k8s.gcr.io/ingress-nginx/controller:v0.49.3@sha256:35fe394c82164efa8f47f3ed0be981b3f23da77175bbb8268a9ae438851c8324"

  #! oauth2-proxy
  - "quay.io/oauth2-proxy/oauth2-proxy:v7.2.0"

  #! kubernetes-dashboard
  - "kubernetesui/dashboard:v2.0.5"
  - "kubernetesui/metrics-scraper:v1.0.6"

  #! grafana
  - "busybox:1.31.1"
  - "grafana/grafana:7.3.1"

  #! metrics-server
  - "k8s.gcr.io/metrics-server/metrics-server:v0.5.2"

  #! kube-state-metrics
  - "k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.2.4"

  #! loki
  - "grafana/loki:1.6.0"
  - "grafana/promtail:1.6.0"

  #! prometheus
  - "jimmidyson/configmap-reload:v0.4.0"
  - "prom/alertmanager:v0.21.0"
  - "prom/node-exporter:v1.0.1"
  - "prom/prometheus:v2.21.0"
  - "prom/pushgateway:v1.2.0"

  #! prometheus-msteams
  - "quay.io/prometheusmsteams/prometheus-msteams:v1.4.1"

  #! minecraft
  - "itzg/minecraft-server:2021.5.1-java8"
  - "itzg/mc-backup:latest"

  #! syncthing
  - "busybox:1.32.0"
  - "syncthing/syncthing:1.11.1"

  #! adguardhome
  - "adguard/adguardhome:v0.106.3"

  #! wireguard
  - "index.docker.io/masipcat/wireguard-go@sha256:972b15ba139b3e612d96c80ebc7fc4e8e63b1b54b4afe9a14049660ef94247f8"
