#@data/values
---
image_puller:
  image: "jamesclonk/image-puller:ef9d2a272282c4ccb199d146e71a4d8fbbdad15c"

  cronjob: true
  run_job: false

  images:
  #! direct jc.io stuff
  - "jamesclonk/image-puller:ef9d2a272282c4ccb199d146e71a4d8fbbdad15c"
  - "jamesclonk/repo-mirrorer:83548d8c17618a57d377467eea8e34264be3dde4"
  - "jamesclonk/backman:2.0.0"
  - "jamesclonk/cf-env:89d20c44e3d6b1a4e0c0502e9d1f5bc908e81264"
  - "jamesclonk/home-info-dashboard:51d910eec8ee81b6ed546d4972ec15f3c67fd1a6"
  - "jamesclonk/irvisualizer:625399ccc65d3eea2b06f2536d41a77b1cc876df"
  - "jamesclonk/ircollector:571721fe7796bb80b571db9e325405a4c531e8a1"
  - "jamesclonk/irdiscordbot:c032a58d922d3f71ee0bc39c4821e97bbd7a9ca0"
  - "jamesclonk/jcio-frontend:942d37e2fadd52c250b1732899aa6566396d4f91"
  - "jamesclonk/moviedb-frontend:87286a8dd8d0ff6fb9108880b51887854ad0872c"
  - "jamesclonk/moviedb-backend:6abf341bd5f1d050e43ac34be3f56b0f72e4af75"
  - "jamesclonk/basic-auth:678636aaca212f20c4e263d05b75efabdc6aef2c"
  - "jamesclonk/pgbackup:aee0398bd7634f209ecd7e1ec03f55002c3c3a57"
  - "jamesclonk/mcbackup:f3b390668671bba69835320ab82824470f6404a4"
  - "jamesclonk/resume:7b30c92e6787eddaec36a9335d3d421c681e0efe"
  - "jamesclonk/item-monitor:1022361"
  - "jamesclonk/prometheus-msteams:workflows"

  #! other stuff
  - "jamesclonk/web-container:latest"
  - "jamesclonk/docker-simple:latest"

  #! hcloud-csi
  - "hetznercloud/hcloud-csi-driver:1.6.0"
  - "k8s.gcr.io/sig-storage/csi-attacher:v3.2.1"
  - "k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.2.0"
  - "k8s.gcr.io/sig-storage/csi-provisioner:v2.2.2"
  - "k8s.gcr.io/sig-storage/csi-resizer:v1.2.0"
  - "k8s.gcr.io/sig-storage/livenessprobe:v2.3.0"

  #! kuard
  - "gcr.io/kuar-demo/kuard-amd64:v0.10.0-green"

  #! postgres
  - "edoburu/pgbouncer:1.12.0"
  - "postgres:12"
  - "wrouesnel/postgres_exporter:v0.8.0"

  #! pgweb
  - "sosedoff/pgweb:0.11.7"

  #! cert-manager
  - "quay.io/jetstack/cert-manager-cainjector:v1.9.1"
  - "quay.io/jetstack/cert-manager-controller:v1.9.1"
  - "quay.io/jetstack/cert-manager-webhook:v1.9.1"

  #! ingress-nginx
  - "registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20220916-gd32f8c343@sha256:39c5b2e3310dc4264d638ad28d9d1d96c4cbb2b2dcfb52368fe4e3c63f61e10f"
  - "jamesclonk/basic-auth:678636aaca212f20c4e263d05b75efabdc6aef2c"
  - "registry.k8s.io/ingress-nginx/controller:v1.4.0@sha256:34ee929b111ffc7aa426ffd409af44da48e5a0eea1eb2207994d9e0c0882d143"

  #! oauth2-proxy
  - "quay.io/oauth2-proxy/oauth2-proxy:v7.2.1"

  #! kubernetes-dashboard
  - "kubernetesui/dashboard:v2.6.1"
  - "kubernetesui/metrics-scraper:v1.0.8"

  #! grafana
  - "busybox:1.31.1"
  - "grafana/grafana:9.2.0"

  #! metrics-server
  - "k8s.gcr.io/metrics-server/metrics-server:v0.5.2"

  #! kube-state-metrics
  - "k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.6.0"

  #! loki
  - "grafana/loki:2.6.1"
  - "docker.io/grafana/promtail:2.6.1"

  #! prometheus
  - "jimmidyson/configmap-reload:v0.5.0"
  - "quay.io/prometheus/alertmanager:v0.24.0"
  - "quay.io/prometheus/node-exporter:v1.3.1"
  - "quay.io/prometheus/prometheus:v2.39.1"
  - "prom/pushgateway:v1.4.3"

  #! prometheus-msteams
  - "quay.io/prometheusmsteams/prometheus-msteams:v1.4.1"

  #! minecraft
  - "itzg/minecraft-server:2021.5.1-java8"
  - "itzg/mc-backup:latest"

  #! syncthing
  - "busybox:1.32.0"
  - "syncthing/syncthing:1.11.1"

  #! adguardhome
  - "adguard/adguardhome:v0.106.3"

  #! wireguard
  - "index.docker.io/masipcat/wireguard-go@sha256:972b15ba139b3e612d96c80ebc7fc4e8e63b1b54b4afe9a14049660ef94247f8"
