#@ load("@ytt:data", "data")
#@ load("_ytt.lib.yml", "labels")

#@ if data.values.cf_env.replicas > 1:
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: cf-env
  namespace: cf-env
  labels: #@ labels("pdb")
spec:
  minAvailable: 50%
  selector:
    matchLabels: #@ labels("app")
#@ end
