#@ load("@ytt:data", "data")
#@ load("_ytt.lib.yml", "labels")

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
  namespace: minecraft
  labels: #@ labels("server")
spec:
  serviceName: minecraft-headless
  selector:
    matchLabels: #@ labels("server")
  replicas: 1
  revisionHistoryLimit: 5
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels: #@ labels("server")
    spec:
      serviceAccountName: minecraft
      securityContext:
        runAsUser: 1000
        runAsGroup: 2000
        fsGroup: 2000
      containers:
      - name: minecraft
        image: #@ data.values.minecraft.image
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 25565
        env:
        - name: TZ
          value: "Europe/Zurich"
        - name: EULA
          value: "true"
        - name: VERSION
          value: "1.16.4"
        - name: TYPE
          value: "FORGE"
        - name: FORGEVERSION
          value: "35.1.4"
        - name: ENABLE_AUTOPAUSE
          value: "true"
        - name: SERVER_NAME
          value: "The JamesClonk Minecraft Server"
        - name: DIFFICULTY
          value: "easy"
        - name: OPS
          value: "JamesClonk"
        - name: WHITELIST
          value: "JamesClonk"
        - name: MOTD
          value: "The JamesClonk Minecraft Server"
        - name: ICON
          value: "https://jamesclonk.io/images/jamesclonk_coa.png"
        - name: OVERRIDE_ICON
          value: "true"
        - name: MAX_PLAYERS
          value: "8"
        - name: MAX_WORLD_SIZE
          value: "33333"
        - name: ALLOW_NETHER
          value: "true"
        - name: ANNOUNCE_PLAYER_ACHIEVEMENTS
          value: "true"
        - name: ENABLE_COMMAND_BLOCK
          value: "true"
        - name: FORCE_GAMEMODE
          value: "true"
        - name: GENERATE_STRUCTURES
          value: "true"
        - name: HARDCORE
          value: "false"
        - name: SNOOPER_ENABLED
          value: "false"
        - name: ALLOW_FLIGHT
          value: "false"
        - name: MAX_BUILD_HEIGHT
          value: "256"
        - name: MAX_TICK_TIME
          value: "60000"
        - name: SPAWN_ANIMALS
          value: "true"
        - name: SPAWN_MONSTERS
          value: "true"
        - name: SPAWN_NPCS
          value: "true"
        - name: VIEW_DISTANCE
          value: "10"
        - name: MODE
          value: "survival"
        - name: PVP
          value: "true"
        - name: LEVEL_TYPE
          value: "default"
        - name: LEVEL
          value: "world"
        - name: ONLINE_MODE
          value: "true"
        - name: MEMORY
          value: "2G"
        - name: ENABLE_RCON
          value: "false"
        - name: ENABLE_QUERY
          value: "false"
        - name: PLAYER_IDLE_TIMEOUT
          value: "30"
        - name: BROADCAST_CONSOLE_TO_OPS
          value: "true"
        - name: BROADCAST_RCON_TO_OPS
          value: "true"
        - name: OP_PERMISSION_LEVEL
          value: "true"
        - name: ENFORCE_WHITELIST
          value: "true"
        - name: GUI
          value: "false"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "3Gi"
            cpu: "3500m"
        startupProbe:
          tcpSocket:
            port: 25565
          failureThreshold: 30
          periodSeconds: 15
        readinessProbe:
          exec:
            command:
            - mcstatus
            - localhost
            - ping
          initialDelaySeconds: 15
          periodSeconds: 15
        livenessProbe:
          exec:
            command:
            - mcstatus
            - localhost
            - ping
          initialDelaySeconds: 15
          periodSeconds: 15
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: minecraft
