#@ load("@ytt:data", "data")
#@ load("_ytt.lib.yml", "labels")

#@ if data.values.pgweb.replicas > 1:
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: pgweb
  namespace: pgweb
  labels: #@ labels("pdb")
spec:
  minAvailable: 50%
  selector:
    matchLabels: #@ labels("dashboard")
#@ end
