#@ load("@ytt:data", "data")
#@ load("_ytt.lib.yml", "labels", "connstr")

---
apiVersion: v1
kind: Secret
metadata:
  name: pgweb
  namespace: pgweb
  labels: #@ labels("secret")
  annotations:
    kapp.k14s.io/versioned: ""
type: Opaque
stringData:
  #@yaml/text-templated-strings
  home_info.toml: |
    url = "(@= connstr(data.values.databases.home_info.username, data.values.databases.home_info.password, data.values.databases.home_info.host, data.values.databases.home_info.db_name) @)"
  #@yaml/text-templated-strings
  irvisualizer.toml: |
    url = "(@= connstr(data.values.databases.irvisualizer.username, data.values.databases.irvisualizer.password, data.values.databases.irvisualizer.host, data.values.databases.irvisualizer.db_name) @)"
  #@yaml/text-templated-strings
  jcio.toml: |
    url = "(@= connstr(data.values.databases.jcio.username, data.values.databases.jcio.password, data.values.databases.jcio.host, data.values.databases.jcio.db_name) @)"
