#@ load("@ytt:data", "data")
#@ load("@ytt:struct", "struct")
#@ load("@ytt:assert", "assert")
#@ load("_ytt.lib.yml", "labels", "connstr")

#@ if len(struct.decode(data.values.databases).keys()) == 0:
#@   assert.fail("databases are missing")
#@ end
#@ for key in struct.decode(data.values.databases).keys():
#@   db = getattr(data.values.databases, key)
#@   if len(db.host) == 0 or db.host == "host":
#@     assert.fail("backman.postgres[" + key + "].host is missing or invalid")
#@   end
#@   if len(db.db_name) == 0 or db.db_name == "dbname":
#@     assert.fail("backman.postgres[" + key + "].db_name is missing or invalid")
#@   end
#@   if len(db.username) == 0 or db.username == "username":
#@     assert.fail("backman.postgres[" + key + "].username is missing or invalid")
#@   end
#@   if len(db.password) == 0 or db.password == "password":
#@     assert.fail("backman.postgres[" + key + "].password is missing or invalid")
#@   end
#@ end
---
apiVersion: v1
kind: Secret
metadata:
  name: pgweb
  namespace: pgweb
  labels: #@ labels("secret")
  annotations:
    kapp.k14s.io/versioned: ""
type: Opaque
stringData:
  #@yaml/text-templated-strings
  #@ for key in struct.decode(data.values.databases).keys():
  #@   db = getattr(data.values.databases, key)
  (@= key @).toml: |
    url = "(@= connstr(db.username, db.password, db.host, db.db_name) @)"
  #@ end
