#@data/values
---
minecraft:
  image: "itzg/minecraft-server:2021.5.1-java8"

  storage:
    #! class_name: hcloud-volumes
    class_name: local-path
    driver: csi.hetzner.cloud
    size: 10Gi
    reclaim: false
    volume_handle: "" # <-- must be set if 'reclaim=true'

  enable_network_policy: true

backup:
  image: "jamesclonk/mcbackup:f3b390668671bba69835320ab82824470f6404a4"
