#@data/values
---
minecraft:
  image: "itzg/minecraft-server:2021.5.1-java8"

  storage:
    class_name: hcloud-volumes
    driver: csi.hetzner.cloud
    size: 10Gi
    reclaim: false
    volume_handle: "" # <-- must be set if 'reclaim=true'

  enable_network_policy: true

  rcon_password: "${MINECRAFT_RCON_PASSWORD}"

backup:
  image: "jamesclonk/mcbackup:f3b390668671bba69835320ab82824470f6404a4"

  s3:
    access_key_id: "${MINECRAFT_S3_BACKUP_ACCESS_KEY}"
    secret_access_key: "${MINECRAFT_S3_BACKUP_SECRET_KEY}"
    endpoint: "${MINECRAFT_S3_BACKUP_ENDPOINT}"
    bucket: "${MINECRAFT_S3_BACKUP_BUCKET}"
