#@ load("@ytt:data", "data")
#@ load("_ytt.lib.yml", "labels")

---
apiVersion: v1
kind: Secret
metadata:
  name: jcio
  namespace: jcio
  labels: #@ labels("secret")
  annotations:
    kapp.k14s.io/versioned: ""
type: Opaque
#@yaml/text-templated-strings
stringData:
  JCIO_HTTP_HMAC_SECRET: #@ data.values.moviedb.hmac_secret
  JCIO_DATABASE_TYPE: postgres
  VCAP_SERVICES: |
    {
      "user-provided": [
       {
        "credentials": {
         "uri": "(@= data.values.moviedb.backend.db_uri @)"
        },
        "label": "user-provided",
        "name": "moviedb"
       }
      ]
    }
