#@ load("@ytt:data", "data")
#@ load("_ytt.lib.yml", "labels")

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: syncthing
  namespace: syncthing
  labels: #@ labels("ingress")
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/auth-url: http://basic-auth.ingress-nginx.svc.cluster.local:8080
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - Ingress"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Authorization "";
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - secretName: syncthing-tls
    hosts:
    #@ for/end host in data.values.domains:
    - #@ "syncthing." + host
  rules:
  #@ for/end host in data.values.domains:
  - host: #@ "syncthing." + host
    http:
      paths:
      - backend:
          serviceName: syncthing-gui
          servicePort: 8384
