#@ load("@ytt:data", "data")
#@ load("@ytt:assert", "assert")
#@ load("_ytt.lib.yml", "labels")

#@ if len(data.values.syncthing.username) == 0:
#@  assert.fail("data.values.syncthing.username cannot be empty")
#@ end
#@ if len(data.values.syncthing.password) == 0:
#@  assert.fail("data.values.syncthing.password cannot be empty")
#@ end
---
apiVersion: v1
kind: Secret
metadata:
  name: syncthing
  namespace: syncthing
  labels: #@ labels("secret")
  annotations:
    kapp.k14s.io/versioned: ""
type: Opaque
#@yaml/text-templated-strings
stringData:
  config.xml: |
    <configuration version="32">
        <gui enabled="true" tls="false" debugging="false">
            <address>0.0.0.0:8384</address>
            <apikey>(@= data.values.syncthing.username @)-(@= data.values.syncthing.password @)</apikey>
            <theme>default</theme>
        </gui>
        <options>
            <listenAddress>tcp://0.0.0.0:22000</listenAddress>
            <listenAddress>quic://0.0.0.0:22000</listenAddress>
            <listenAddress>dynamic+https://relays.syncthing.net/endpoint</listenAddress>
            <globalAnnounceEnabled>false</globalAnnounceEnabled>
            <localAnnounceEnabled>false</localAnnounceEnabled>
            <reconnectionIntervalS>60</reconnectionIntervalS>
            <relaysEnabled>false</relaysEnabled>
            <startBrowser>false</startBrowser>
            <natEnabled>false</natEnabled>
            <urAccepted>-1</urAccepted>
            <urPostInsecurely>false</urPostInsecurely>
            <urInitialDelayS>1800</urInitialDelayS>
            <restartOnWakeup>true</restartOnWakeup>
            <autoUpgradeIntervalH>0</autoUpgradeIntervalH>
            <stunKeepaliveSeconds>0</stunKeepaliveSeconds>
            <defaultFolderPath></defaultFolderPath>
        </options>
        <folder id="default" label="Sync" path="/var/syncthing/sync" type="sendreceive" rescanIntervalS="3600" fsWatcherEnabled="true" fsWatcherDelayS="10" ignorePerms="false" autoNormalize="true">
            <filesystemType>basic</filesystemType>
            <minDiskFree unit="%">2</minDiskFree>
            <versioning></versioning>
            <copiers>0</copiers>
            <pullerMaxPendingKiB>0</pullerMaxPendingKiB>
            <hashers>0</hashers>
            <order>random</order>
            <ignoreDelete>false</ignoreDelete>
            <scanProgressIntervalS>0</scanProgressIntervalS>
            <pullerPauseS>0</pullerPauseS>
            <maxConflicts>-1</maxConflicts>
            <disableSparseFiles>false</disableSparseFiles>
            <disableTempIndexes>false</disableTempIndexes>
            <paused>false</paused>
            <weakHashThresholdPct>25</weakHashThresholdPct>
            <markerName>.stfolder</markerName>
            <copyOwnershipFromParent>false</copyOwnershipFromParent>
            <modTimeWindowS>0</modTimeWindowS>
            <maxConcurrentWrites>2</maxConcurrentWrites>
            <disableFsync>false</disableFsync>
            <blockPullOrder>standard</blockPullOrder>
            <copyRangeMethod>standard</copyRangeMethod>
            <caseSensitiveFS>false</caseSensitiveFS>
            <junctionsAsDirs>false</junctionsAsDirs>
        </folder>
    </configuration>
