#@ load("@ytt:data", "data")
#@ load("_ytt.lib.yml", "labels")

#@ if data.values.kuard.replicas > 1:
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: kuard
  namespace: kuard
  labels: #@ labels("pdb")
spec:
  minAvailable: 50%
  selector:
    matchLabels: #@ labels("app")
#@ end
