#@ load("@ytt:data", "data")
#@ load("@ytt:assert", "assert")
#@ load("_ytt.lib.yml", "labels")

#@ if len(data.values.secrets.repo_mirrorer.gitlab_token) == 0 or data.values.secrets.repo_mirrorer.gitlab_token == "token":
#@  assert.fail("secrets.repo_mirrorer.gitlab_token is missing or invalid")
#@ end
---
apiVersion: v1
kind: Secret
metadata:
  name: repo-mirrorer-secret
  namespace: repo-mirrorer
  labels: #@ labels()
  annotations:
    kapp.k14s.io/versioned: ""
type: Opaque
stringData:
  gitlab-token: #@ data.values.secrets.repo_mirrorer.gitlab_token
