#@ load("@ytt:data", "data")
#@ load("_ytt.lib.yml", "labels")

---
apiVersion: v1
kind: Secret
metadata:
  name: repo-mirrorer-secret
  namespace: repo-mirrorer
  labels: #@ labels()
  annotations:
    kapp.k14s.io/versioned: ""
type: Opaque
stringData:
  gitlab-token: #@ data.values.repo_mirrorer.gitlab_token
