name: adguardhome dns adblocker

on:
  workflow_dispatch:

jobs:
  adguardhome:
    name: adguardhome
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: deploy adguardhome dns
      working-directory: adguardhome
      run: ./deploy.sh
      env:
        SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
    - name: cleanup
      if: ${{ always() }}
      run: ./cleanup.sh
