name: kubernetes deployments

on:
  push:
    branches: [ master ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  cf-env:
    if: "!contains(github.event.head_commit.message, 'skip')"
    name: cf-env
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: deploy cf-env demo app
      working-directory: cf-env
      run: ./deploy.sh

  kuard:
    if: "!contains(github.event.head_commit.message, 'skip')"
    name: kuard
    needs: [ cf-env ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: deploy kuard demo app
      working-directory: kuard
      run: ./deploy.sh

  pgweb:
    if: "!contains(github.event.head_commit.message, 'skip')"
    name: pgweb
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: deploy pgweb postgres admin ui
      working-directory: pgweb
      run: ./deploy.sh

  backman:
    if: "!contains(github.event.head_commit.message, 'skip')"
    name: backman
    needs: [ pgweb ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: deploy backman postgres backup app
      working-directory: backman
      run: ./deploy.sh

  jcio:
    if: "!contains(github.event.head_commit.message, 'skip')"
    name: jcio
    needs: [ backman ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: deploy jcio homepage app
      working-directory: jcio
      run: ./deploy.sh

  home-info:
    if: "!contains(github.event.head_commit.message, 'skip')"
    name: home-info
    needs: [ backman ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: deploy home-info app
      working-directory: home-info
      run: ./deploy.sh

  irvisualizer:
    if: "!contains(github.event.head_commit.message, 'skip')"
    name: irvisualizer
    needs: [ backman ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: deploy iRacing visualization app
      working-directory: irvisualizer
      run: ./deploy.sh

  syncthing:
    if: "!contains(github.event.head_commit.message, 'skip')"
    name: syncthing
    needs: [ kuard ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: deploy syncthing server
      working-directory: syncthing
      run: ./deploy.sh

  minecraft:
    if: "!contains(github.event.head_commit.message, 'skip')"
    name: minecraft
    needs: [ kuard ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: deploy minecraft server
      working-directory: minecraft
      run: ./deploy.sh

  image-puller:
    if: "!contains(github.event.head_commit.message, 'skip')"
    name: image-puller
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: deploy image-puller cronjob
      working-directory: image-puller
      run: ./deploy.sh

  repo-mirrorer:
    if: "!contains(github.event.head_commit.message, 'skip')"
    name: repo-mirrorer
    needs: [ image-puller ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: deploy repo-mirrorer cronjob
      working-directory: repo-mirrorer
      run: ./deploy.sh
