name: Kubernetes Deployments

on:
  push:
    branches: [ master ]

jobs:
  env:
    KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}
    INGRESS_DOMAIN: ${{ secrets.INGRESS_DOMAIN }}

  cf-env:
    if: "!contains(github.event.head_commit.message, 'skip')"
    name: cf-env
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy cf-env
      working-directory: cf-env
      run: ./deploy.sh
