name: kubernetes deployments

on:
  push:
    branches: [ master ]

env:
  KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}
  INGRESS_DOMAIN: ${{ secrets.INGRESS_DOMAIN }}
  INGRESS_BASIC_AUTH_USERNAME: ${{ secrets.INGRESS_BASIC_AUTH_USERNAME }}
  INGRESS_BASIC_AUTH_PASSWORD: ${{ secrets.INGRESS_BASIC_AUTH_PASSWORD }}

jobs:
  cf-env:
    if: "!contains(github.event.head_commit.message, 'skip')"
    name: cf-env
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: deploy cf-env demo app
      working-directory: cf-env
      run: ./deploy.sh

  kuard:
    if: "!contains(github.event.head_commit.message, 'skip')"
    name: kuard
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: deploy kuard demo app
      working-directory: kuard
      run: ./deploy.sh

  image-puller:
    if: "!contains(github.event.head_commit.message, 'skip')"
    name: image-puller
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: deploy image-puller cronjob
      working-directory: image-puller
      run: ./deploy.sh
