name: backman - postgres backup application

on:
  workflow_dispatch:

jobs:
  backman:
    name: backman
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: deploy backman postgres backup app
      working-directory: backman
      run: ./deploy.sh
      env:
        SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
    - name: cleanup
      if: ${{ always() }}
      run: ./cleanup.sh
