name: cf-env demo application

on:
  workflow_dispatch:

jobs:
  cf-env:
    name: cf-env
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: deploy cf-env demo app
      working-directory: cf-env
      run: ./deploy.sh
      env:
        SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
    - name: cleanup
      if: ${{ always() }}
      run: ./cleanup.sh
