name: home-info - home automation application

on:
  workflow_dispatch:

jobs:
  home-info:
    name: home-info
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: deploy home-info app
      working-directory: home-info
      run: ./deploy.sh
      env:
        SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
    - name: cleanup
      if: ${{ always() }}
      run: ./cleanup.sh
