name: home-info - home automation application

on:
  workflow_dispatch:

jobs:
  home-info:
    name: home-info
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: deploy home-info app
      working-directory: home-info
      run: ./deploy.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
    - name: cleanup
      if: ${{ always() }}
      run: ./cleanup.sh
