name: image-puller cronjob

on:
  workflow_dispatch:

jobs:
  image-puller:
    name: image-puller
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: deploy image-puller cronjob
      working-directory: image-puller
      run: ./deploy.sh
      env:
        SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
    - name: cleanup
      if: ${{ always() }}
      run: ./cleanup.sh
