name: irvisualizer application

on:
  workflow_dispatch:

jobs:
  irvisualizer:
    name: irvisualizer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: deploy iRacing visualization app
      working-directory: irvisualizer
      run: ./deploy.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
    - name: cleanup
      if: ${{ always() }}
      run: ./cleanup.sh
