name: irvisualizer application

on:
  workflow_dispatch:

jobs:
  irvisualizer:
    name: irvisualizer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: deploy iRacing visualization app
      working-directory: irvisualizer
      run: ./deploy.sh
      env:
        SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
    - name: cleanup
      if: ${{ always() }}
      run: ./cleanup.sh
