name: jcio - homepage application

on:
  workflow_dispatch:

jobs:
  jcio:
    name: jcio
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: deploy jcio homepage app
      working-directory: jcio
      run: ./deploy.sh
      env:
        SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
    - name: cleanup
      if: ${{ always() }}
      run: ./cleanup.sh
