name: kuard demo application

on:
  workflow_dispatch:

jobs:
  kuard:
    name: kuard
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: deploy kuard demo app
      working-directory: kuard
      run: ./deploy.sh
      env:
        SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
    - name: cleanup
      if: ${{ always() }}
      run: ./cleanup.sh
