name: kuard demo application

on:
  workflow_dispatch:

jobs:
  kuard:
    name: kuard
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: deploy kuard demo app
      working-directory: kuard
      run: ./deploy.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
