name: minecraft server

on:
  workflow_dispatch:

jobs:
  minecraft:
    name: minecraft
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: deploy minecraft server
      working-directory: minecraft
      run: ./deploy.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}

        MINECRAFT_RCON_PASSWORD: ${{ secrets.MINECRAFT_RCON_PASSWORD }}
        MINECRAFT_S3_BACKUP_ACCESS_KEY: ${{ secrets.MINECRAFT_S3_BACKUP_ACCESS_KEY }}
        MINECRAFT_S3_BACKUP_SECRET_KEY: ${{ secrets.MINECRAFT_S3_BACKUP_SECRET_KEY }}
        MINECRAFT_S3_BACKUP_ENDPOINT: ${{ secrets.MINECRAFT_S3_BACKUP_ENDPOINT }}
        MINECRAFT_S3_BACKUP_BUCKET: ${{ secrets.MINECRAFT_S3_BACKUP_BUCKET }}
