name: minecraft server

on:
  workflow_dispatch:

jobs:
  minecraft:
    name: minecraft
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: deploy minecraft server
      working-directory: minecraft
      run: ./deploy.sh
      env:
        SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
    - name: cleanup
      if: ${{ always() }}
      run: ./cleanup.sh
