name: pbweb - postgres admin ui

on:
  workflow_dispatch:

jobs:
  pgweb:
    name: pgweb
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: deploy pgweb postgres admin ui
      working-directory: pgweb
      run: ./deploy.sh
      env:
        SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
    - name: cleanup
      if: ${{ always() }}
      run: ./cleanup.sh
