name: repo-mirrorer cronjob

on:
  workflow_dispatch:

jobs:
  repo-mirrorer:
    name: repo-mirrorer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: deploy repo-mirrorer cronjob
      working-directory: repo-mirrorer
      run: ./deploy.sh
      env:
        SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
    - name: cleanup
      if: ${{ always() }}
      run: ./cleanup.sh
