name: repo-mirrorer cronjob

on:
  workflow_dispatch:

jobs:
  repo-mirrorer:
    name: repo-mirrorer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: deploy repo-mirrorer cronjob
      working-directory: repo-mirrorer
      run: ./deploy.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
    - name: cleanup
      if: ${{ always() }}
      run: ./cleanup.sh
