name: resume web application

on:
  workflow_dispatch:

jobs:
  resume:
    name: resume
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: deploy resume web app
      working-directory: resume
      run: ./deploy.sh
      env:
        SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
    - name: cleanup
      if: ${{ always() }}
      run: ./cleanup.sh
