name: syncthing file server

on:
  workflow_dispatch:

jobs:
  syncthing:
    name: syncthing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: deploy syncthing server
      working-directory: syncthing
      run: ./deploy.sh
      env:
        SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
    - name: cleanup
      if: ${{ always() }}
      run: ./cleanup.sh
