name: syncthing file server

on:
  workflow_dispatch:

jobs:
  syncthing:
    name: syncthing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: deploy syncthing server
      working-directory: syncthing
      run: ./deploy.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}

        INGRESS_DOMAIN: ${{ secrets.INGRESS_DOMAIN }}
        SYNCTHING_USERNAME: ${{ secrets.SYNCTHING_USERNAME }}
        SYNCTHING_PASSWORD: ${{ secrets.SYNCTHING_PASSWORD }}
