name: wireguard vpn server

on:
  workflow_dispatch:

jobs:
  wireguard:
    name: wireguard
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: deploy wireguard server
      working-directory: wireguard
      run: ./deploy.sh
      env:
        SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
    - name: cleanup
      if: ${{ always() }}
      run: ./cleanup.sh
